### PR TITLE
Increase flysystem minimum version

### PR DESCRIPTION
**Pull request by krenor**
See https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm

### CODE REVIEW

**Review by pvsaintpe — APPROVED** [review]

**Comment by bssanchez** [comment]
bump!

**Comment by frankdejonge** [comment]
Thank you kindly. However, I just wanted to let you know that this is not needed. Dependency resolving fixes this, the fixed version is included in the constraint.

Tip for @bssanchez: bumping issues is in the top 5 of maintainer frustrations, it makes maintainers want to do the thing you want them to do less. Please stop doing it.

**Comment by krenor** [comment]
Care to elaborate @frankdejonge? Shouldn't this be required to guarantee nobody installs a version lower than 1.1.4? Or am I missing something? 👀

**Comment by frankdejonge** [comment]
Hi @krenor,

The version constraint includes the fixed version, so there is not a blocker. The consumer of this library should always have a direct dependency on the main library as well. When users upgrade their dependencies, they'll get the fixed version. We can do a new release for this package, but unless they do an upgrade (which would have fixed the issue for them regardless of this fix) they won't get this upgrade either. So all the upgrade scenarios are just the same, it's just more steps and more management for me.

Even in the scenario where somebody only depends on this package, a dependency upgrade would fix this. And if they don't do that they wouldn't have gotted this "fixed" version either.

**Pull request closed without merging**
