### PR TITLE
Update and rename LICENCE to LICENSE

### PR DESCRIPTION
**Pull request by dereuromark**
Legal issue: Typo in file name and missing header for clarification as per default guidelines.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Hi @dereuromark, license (American English) and licence (British English) are both correct.

**Comment by frankdejonge** [comment]
I'll merge to add the explicit licen(s|c)e type .

**Comment by dereuromark** [comment]
Language wise, true :)
But in coding, the convention is usually AE here (color vs colour, and more).
Thank you! :)

**Comment by frankdejonge** [comment]
@dereuromark it's all the same for me, in any case it's not a legal issue.

**Comment by dereuromark** [comment]
For us it was :) Since we were looking into all used MIT repos we use and couldnt parse a license on yours - I found then out why^^

**Comment by mndayizeye** [comment]
well
#155

**Pull request merged**
