### PR TITLE
Get a shallow list of objects in listContents

### PR DESCRIPTION
**Pull request by zaak**
This is a performance improvement like in https://github.com/thephpleague/flysystem-aws-s3-v2/pull/13.
With AWS-SDK v3 it's not possible to pass `return_prefixes` iterator option, so I had to process the command _manually_. Actually it may be even more efficient as there's no unnecessary array to iterator, and then back iterator to array conversion.

### CODE REVIEW

**Comment by basz** [comment]
I've confirmed this patch to be much much much faster then before. Thnx!

**Comment by frankdejonge** [comment]
@zaak I'm doing some research of my own as well, I know that this implementation might have the 1000 object limit, which is something the iterator works around. Might be that we'll need to file an issue for this and require at least the next version or implement it ourselves.

**Comment by zaak** [comment]
@frankdejonge Good to know. I'll have a look at this too.

**Comment by zaak** [comment]
@frankdejonge I've updated the PR (just to let you know what I found). Looks like [paginators](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/paginators.html) may be the way to go. Seems to work fine with > 1000 objects, but I didn't do too much testing yet.

**Comment by basz** [comment]
this works fine (a tests fails though) - is this to be released anytime soon?

**Comment by zaak** [comment]
@basz Which tests fails?

**Comment by zaak** [comment]
Updated the PR. It's kinda tricky to test it properly due to internal closure. But I think it's worth to keep it this way and allow requests to be sent asynchronously.

**Pull request merged**
