### PR TITLE
Add a new method "getPresignedUrl"

### PR DESCRIPTION
**Pull request by grizzlylab**
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html#creating-a-presigned-url

### CODE REVIEW

**Comment by neilcrookespm** [comment]
This would be useful for me. It would be great if you could add it?

**Comment by kamranahmedse** [comment]
Ping @frankdejonge

**Comment by frankdejonge** [comment]
This doesn't really belong in Flysystem. It's only applicable to S3. There's a case to be made to have a DX layer for the AWS PHP SDK, but Flysystem is not the place for it. I'd recommend opening up an issue on the SDK repo for this and use the SDK directly.

**Comment by grizzlylab** [comment]
Indeed. @neilcrookespm You can just extend League\Flysystem\AwsS3v3\AwsS3Adapter and add this tiny method by yourself. This is what I did in my project.

**Comment by frankdejonge** [comment]
@grizzlylab that's one option. Alternatively you can use the Plugin mechanism to expose this on the Filesystem level, so no need to use the adapter directly (which is also advised not to do).

**Comment by grizzlylab** [comment]
Ok

**Pull request closed without merging**
