### PR TITLE
Update AwsS3Adapter.php

### PR DESCRIPTION
**Pull request by Apologiz**
Add setters for bucket, client and options.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@Apologiz an adapter should not be re-used for different s3 clients. You should create a new instance for a new flysystem filesystem/adapter combination.

**Comment by Apologiz** [comment]
@frankdejonge, Ok, can make protected setters so they can not be reused? :)

**Comment by frankdejonge** [comment]
@Apologiz then what's the purpose of having them if they're only used in the constructor? I appreciate your willingness to contribute, but I think this PR is not really needed. Hope you understand.

**Comment by Apologiz** [comment]
@frankdejonge, Oh sure. It was purely visual improvement.

**Pull request closed without merging**
