### PR TITLE
Prevent ContentType assignation when dirs are created.

### PR DESCRIPTION
**Pull request by ganeko**
ContentType assignation is not needed for directories and this cause unexpected behavior in third-parties like s3fs.

Using this adapter, if you create a directory and you try to read it via s3fs you get an error because it is managed as a file.

Sample code,

```
$flySystem->createDir('exports://fromFlySystem/')
```

Accessing via s3fs (in other system outside PHP environment),

```
root@xxxxx:/mnt/exports# ls -la
total 1
drwxrwxr-x 1 www-data www-data 0 Jan  1  1970 .
drwxrwxrwx 1 root     root     0 Jan  1  1970 ..
---------- 1 root     root     0 Feb 13 11:59 fromFlySystem
```

```
root@xxxxx:/mnt/exports# file fromFlySystem 
fromFlySystem: empty
```

```
root@xxxxx:/mnt/exports# cd fromFlySystem 
-bash: cd: fromFlySystem: Not a directory
```

### CODE REVIEW

**Comment by frankdejonge** [comment]
Holla! Could you update the tests for this too? Also, just a quick question, why do you create directories on s3?

**Comment by ganeko** [comment]
Hi,

We create directories via this adapter because s3fs' performance is very bad and in order to prevent CPU problems in the other system.

**Comment by frankdejonge** [comment]
Do you actually need the directories? Because s3 itself doesn't need them. What's your use-case?

**Comment by ganeko** [comment]
Yes, because we deploy the same core in different environments with different adapters (Local, S3, etc...) and we need to ensure that the directories exist for the following processes, otherwise, we have to be constantly checking this and as I said, s3fs has performance issues.

**Comment by ganeko** [comment]
Hi @frankdejonge ,

Any chance to keep an eye on the changes I've suggested?.

Thanks!

**Comment by frankdejonge** [comment]
Dude, the PR is 19 hours old.

**Comment by ganeko** [comment]
Oh, sorry.

Yesterday we were having a conversation and I thought it would be more fluid.

Many thanks.

**Comment by frankdejonge** [comment]
Also, I want to first check what the consequences are for DO spaces and AWS S3 itself before merging to see if it doesn't cause regressions. I'm also moving house now so I expect to get to this somewhere next week at the earliest.

**Comment by ganeko** [comment]
Ok, no problem.

Many thanks, and apologies.

**Comment by frankdejonge** [comment]
This is released as 1.0.23

**Comment by ganeko** [comment]
Amazing, thanks a lot!.

**Comment by frankdejonge** [comment]
Thank you for your contribution 👍

**Pull request merged**
