### PR TITLE
replaced argument for upload; adding params as default key in createOptionsFromConfig used for upload and copy

### PR DESCRIPTION
**Pull request by ToshY**
Issue #269

### CODE REVIEW

**Comment by ToshY** [comment]
If there's something not completely correct or up to standard, let me know. I'm still learning so any feedback is much appreciated.

**Comment by ToshY** [comment]
@frankdejonge could you possibly review this?

**Comment by frankdejonge** [comment]
Hi @ToshY the 2.x branch is maintained in the central repository, could you send a PR there? I'll make sure to review it this week.

**Comment by ToshY** [comment]
Ah sorry I wasn't aware of that. I'll make the PR there. Thanks.

**Comment by ToshY** [comment]
New PR: https://github.com/thephpleague/flysystem/pull/1396

**Pull request closed without merging**
